// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/test-notifications": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/test-notifications";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/test-notifications.tsx": {
    id: "routes/test-notifications";
    page: "/test-notifications";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/_index": typeof import("./src/routes/_index.tsx");
  "routes/test-notifications": typeof import("./src/routes/test-notifications.tsx");
};